[package]
name = "example"
version = "0.1.0"
authors = ["Oliver Berzs <oliver.berzs@gmail.com>"]
edition = "2018"

[dependencies]
pretty_env_logger = "0.4.0"
tagne = { path = "../tagne", version = "0.1.0" }