[package]
name = "import"
version = "0.1.0"
authors = ["Oliver Berzs <oliver.berzs@gmail.com>"]
edition = "2018"

[dependencies]
shaderc = "0.6.2"
clap = "2.33.1"
rusttype = "0.9.2"
serde = { version = "1.0.114", features = ["derive"] }
bincode = "1.3.1"
notify = "4.0.15"
