[package]
name = "tegne-utils"
version = "0.1.0"
authors = ["Oliver Berzs <oliver.berzs@gmail.com>"]
edition = "2018"

[dependencies]
winit = "0.22.2"
log = "0.4.8"
tegne-math = { path = "../tegne-math", version = "0.1.0" }
