[package]
name = "example-blue"
version = "0.1.0"
authors = ["Oliver Berzs <oliver.berzs@gmail.com>"]
edition = "2018"

[dependencies]
imgui = "0.3.0"
tegne = { path = "../../tegne", version = "0.1.0" }