name: Binaries

on:
  push:
    branches: [release]

jobs:
  windows:
    name: "Windows"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Ninja
        run: choco install ninja

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.47.0
          override: true

      - name: Build
        run: cargo build --release --bin dc --features="glsl"

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: dc-windows
          path: target/release/dc.exe

  linux:
    name: "Linux"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.47.0
          override: true

      - name: Build
        run: cargo build --release --bin dc --features="glsl"

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: dc-linux
          path: target/release/dc
