name: Check

on:
  push:
    branches: [develop]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check
        working-directory: ./draw-it
        run: cargo check --no-default-features

      - name: Test
        working-directory: ./draw-it
        run: cargo test --no-default-features
