name: Check

on:
  push:
    branches: [develop]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.46.0
          override: true

      - name: Check
        run: cargo check --lib --no-default-features
