name: Check

on:
  pull_request:
    branches: [develop, release]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.47.0
          override: true

      - name: Check
        run: cargo check --no-default-features --lib
