name: Full Build

on: workflow_dispatch

jobs:
  windows:
    name: "Windows"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Ninja
        run: choco install ninja

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

  linux:
    name: "Linux"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install LibX
        run: |
          sudo apt update -y
          sudo apt install -y libxrandr-dev
          sudo apt install -y libxinerama-dev
          sudo apt install -y libxcursor-dev
          sudo apt install -y libxi-dev

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test
