name: Full Linux Build

on: workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      vulkan-version: 1.2.141.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install LibX
        run: |
          sudo apt update -y
          sudo apt install -y libxrandr-dev
          sudo apt install -y libxinerama-dev
          sudo apt install -y libxcursor-dev
          sudo apt install -y libxi-dev

      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test
