name: Full Windows Build

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    env:
      vulkan-version: 1.2.141.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Vulkan SDK
        run: |
          wget https://sdk.lunarg.com/sdk/download/${{env.vulkan-version}}/mac/vulkansdk-mac-${{env.vulkan-version}}.tar.gz
          tar xf vulkansdk-mac-${{env.vulkan-version}}.tar.gz
          sudo cp vulkansdk-macos-${{env.vulkan-version}}/macOS/bin/glslc /usr/local/bin

      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test
