name: Math test

on:
  push:
    branches: [master]
    paths:
      - "tenge-math/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --package tegne-math
