name: Math test

on:
  push:
    branches: [master]
    paths:
      - "tenge-math/**"
      - ".github/workflows/math.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --package tegne-math
