name: Tegne check

on:
  push:
    branches: [master]
    paths:
      - "tenge/**"
      - "tenge-math/**"
      - "tegne-utils/**"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --no-default-features --manifest-path "tegne/Cargo.toml"
