name: Utils check

on:
  push:
    branches: [master]
    paths:
      - "tegne-utils/**"
      - "tegne-math/**"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --package tegne-utils
