name: Utils check

on:
  push:
    branches: [master]
    paths:
      - "tegne-utils/**"
      - "tegne-math/**"
      - ".github/workflows/utils.yml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --package tegne-utils
